### ISSUE TITLE
Write Landmark.php

### ISSUE THREAD

**Issue by emanguy** [OregonTrailGroup/Oregon-Trail-Scripting-Languages#13]
Should show a landmark, town, or river and show appropriate actions given by CommonActions.php's `showActions()` and `showRiverActions()` (see #12).

## Inputs
 * image - the image to display (a URL)
 * name - the name of the landmark
 * isTown - a boolean saying whether or not this is a town

## Outputs

 * Should go to travel.php or lastriver.php when the user wants to travel again based on where they are.

**Comment by emanguy** [comment]
Blocked by #12

**Comment by adamwe1** [comment]
Changing isTown to isRiver because that's more drastic a difference, hasTown can be pulled separately.

**Comment by adamwe1** [comment]
Also just adding hasShop to inputs

**Comment by emanguy** [comment]
You should expect the following query params for crossing rivers:
 * `fording` - ford the river, call the River->ford()
 * `ferrying` - take the ferry, get across automatically and deduct $5 from the user
