### ISSUE TITLE
Random Events

### ISSUE THREAD

**Issue by adamwe1** [OregonTrailGroup/Oregon-Trail-Scripting-Languages#5]
### Random events:
 1. Getting Sick
 2. Wagon parts breaking
 3. Weather changes (including hugely inclement weather)
 4. Thieves stealing just about anything
 5. Finding Wagons
 6. Grave markers

Make RandomEvent.php which updates the session data with a random event it generates. It then returns an object via the following schema based on the events which occur:

```json
{
  "got_sick": {"partyMember": Number (index of party memb), "sickName": String},
  "wagon_broke": {"wagonPart": Number},
  "weather_change": {"weather": String, "slow_factor": Number},
  "thief_steal": { "id": Number, "qty": Number },
  "find_wagon": {/*Same as thief_steal*/},
  "grave_marker": {
    "name": String,
    "message": String,
    "date": String
  }
}
```

**Comment by emanguy** [comment]
Uses functions from #2 so is blocked

**Comment by emanguy** [comment]
Unblocked
